create table if not exists profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  gmail text not null,
  gender text not null,
  created_at timestamp with time zone default now()
);

alter table profiles enable row level security;

drop policy if exists "Allow public insert registrations" on profiles;

create policy "Allow public insert registrations"
on profiles
for insert
to anon
with check (true);
